CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  email VARCHAR,
  name VARCHAR UNIQUE NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY,
  content VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
  author INTEGER REFERENCES users NOT NULL
);

CREATE TABLE IF NOT EXISTS tag_groups (
  id SERIAL PRIMARY KEY,
  name VARCHAR UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  tag_group VARCHAR REFERENCES tag_groups (name) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS posts_tags (
  tag_id INTEGER REFERENCES tags ON DELETE CASCADE,
  post_id INTEGER REFERENCES posts ON DELETE CASCADE,
  PRIMARY KEY (tag_id, post_id)
);

CREATE TABLE IF NOT EXISTS tag_groups_users (
  tag_group_id INTEGER REFERENCES tag_groups ON DELETE CASCADE,
  user_id INTEGER REFERENCES users ON DELETE CASCADE,
  PRIMARY KEY (tag_group_id, user_id)
);